### ISSUE TITLE
Singularity Hub Build API Limit

### ISSUE THREAD

**Issue by vsoch** [dynverse/ti_slice#1]
Heyo! 

I wanted to let you know that your "build on Commit" on Singularity Hub just hit the GitHub webhook API limit, so the builds won't happen until it's refreshed. Since you have it set to build on commit and are committing quite frequently I would recommend that you choose another option such as a manual trigger to avoid this kind of thing. I'm not sure what kind of negative action might come of trying to abuse the API limits but I wouldn't press it to find out :-) Let me know if you have any questions!

**Comment by vsoch** [comment]
@rcannood most operations that you try involving GitHub unfortunately aren't going to work, I'm getting a stream of errors for trying to look at branches and other things. I would perhaps stop for a day and try again. Sorry for the inconvenience, and when it's working again I can offer to help so you don't need to go over the limit (you are the first in 2 years to have this happen, congrats haha)

**Comment by rcannood** [comment]
Hi Vanessa!

Ha! That explains why not much is happening right now. Thanks for letting me know so quickly :) I'll keep an eye on my rate limit.

Each of the separate repositories should only be updated sporadically, so I hope the high amount of API calls will only be a one time thing.

Robrecht

**Comment by vsoch** [comment]
Ok great! Glad to be of help! I take no credit, the robots sent me notification :-) They never sleep!

**Comment by rcannood** [comment]
Sure, but it was you who took the effort of letting me know what was up, not the bots!

Apparently my rate has just been reset. I was almost done creating collections. Is it okay if I try again?

**Comment by rcannood** [comment]
I'm afraid to inform you that I disregarded your previous advice and created more collections! Everything worked just fine :+1: Thanks @vsoch!
